CREATE TABLE IF NOT EXISTS "__EFMigrationsHistory" (
    "MigrationId" character varying(150) NOT NULL,
    "ProductVersion" character varying(32) NOT NULL,
    CONSTRAINT "PK___EFMigrationsHistory" PRIMARY KEY ("MigrationId")
);

START TRANSACTION;

CREATE TABLE "Company" (
    "Id" uuid NOT NULL,
    "Name" text NOT NULL,
    "Description" text,
    "Address" text NOT NULL,
    "Email" text NOT NULL,
    "PhoneNumber" text NOT NULL,
    "Type" integer NOT NULL,
    "Country" text NOT NULL,
    "CreatedAt" timestamp with time zone NOT NULL,
    "UpdatedAt" timestamp with time zone NOT NULL,
    CONSTRAINT "PK_Company" PRIMARY KEY ("Id")
);

CREATE TABLE "Customers" (
    "Id" uuid NOT NULL,
    "Name" text,
    "Email" text NOT NULL,
    "PhoneNumber" text,
    "WhatsAppNumber" text,
    "Address" text,
    "CompanyId" uuid NOT NULL,
    "CreatedAt" timestamp with time zone NOT NULL,
    "UpdatedAt" timestamp with time zone NOT NULL,
    "IsDeleted" boolean NOT NULL,
    CONSTRAINT "PK_Customers" PRIMARY KEY ("Id")
);

CREATE TABLE "Notification" (
    "CompanyId" uuid NOT NULL,
    "Title" text,
    "Message" text,
    "CreatedAt" timestamp with time zone NOT NULL,
    "IsRead" boolean NOT NULL,
    "Type" text
);

CREATE TABLE "Permission" (
    "Id" uuid NOT NULL,
    "Name" text NOT NULL,
    CONSTRAINT "PK_Permission" PRIMARY KEY ("Id")
);

CREATE TABLE "Role" (
    "Id" text NOT NULL,
    "Name" character varying(256),
    "NormalizedName" character varying(256),
    "ConcurrencyStamp" text,
    CONSTRAINT "PK_Role" PRIMARY KEY ("Id")
);

CREATE TABLE "User" (
    "Id" text NOT NULL,
    "CompanyId" uuid,
    "CompanyName" text NOT NULL,
    "RegistrationNumber" text,
    "TaxIdentificationNumber" text,
    "ContactEmail" text,
    "FullName" text,
    "ContactPhone" text,
    "CompanyAddress" text,
    "Type" integer NOT NULL,
    "IsActive" boolean,
    "DisabledBy" text,
    "EnabledBy" text,
    "DateEnabled" timestamp with time zone,
    "DateDisabled" timestamp with time zone,
    "IsDeleted" boolean,
    "DeletedOn" timestamp with time zone,
    "DateCreated" timestamp with time zone,
    "DeletedBy" text,
    "CreatedBy" text NOT NULL,
    "LastUpdated" timestamp with time zone,
    "UpdatedBy" text,
    "UserName" character varying(256),
    "NormalizedUserName" character varying(256),
    "Email" character varying(256),
    "NormalizedEmail" character varying(256),
    "EmailConfirmed" boolean NOT NULL,
    "PasswordHash" text,
    "SecurityStamp" text,
    "ConcurrencyStamp" text,
    "PhoneNumber" text,
    "PhoneNumberConfirmed" boolean NOT NULL,
    "TwoFactorEnabled" boolean NOT NULL,
    "LockoutEnd" timestamp with time zone,
    "LockoutEnabled" boolean NOT NULL,
    "AccessFailedCount" integer NOT NULL,
    CONSTRAINT "PK_User" PRIMARY KEY ("Id"),
    CONSTRAINT "FK_User_Company_CompanyId" FOREIGN KEY ("CompanyId") REFERENCES "Company" ("Id") ON DELETE RESTRICT
);

CREATE TABLE "RoleClaim" (
    "Id" integer GENERATED BY DEFAULT AS IDENTITY,
    "RoleId" text NOT NULL,
    "ClaimType" text,
    "ClaimValue" text,
    CONSTRAINT "PK_RoleClaim" PRIMARY KEY ("Id"),
    CONSTRAINT "FK_RoleClaim_Role_RoleId" FOREIGN KEY ("RoleId") REFERENCES "Role" ("Id") ON DELETE CASCADE
);

CREATE TABLE "RolePermission" (
    "RoleId" text NOT NULL,
    "PermissionId" uuid NOT NULL,
    CONSTRAINT "PK_RolePermission" PRIMARY KEY ("RoleId", "PermissionId"),
    CONSTRAINT "FK_RolePermission_Permissions_PermissionId" FOREIGN KEY ("PermissionId") REFERENCES "Permission" ("Id") ON DELETE CASCADE,
    CONSTRAINT "FK_RolePermission_Roles_RoleId" FOREIGN KEY ("RoleId") REFERENCES "Role" ("Id") ON DELETE CASCADE
);

CREATE TABLE "Order" (
    "Id" uuid NOT NULL,
    "Status" integer NOT NULL,
    "CreatedAt" timestamp with time zone NOT NULL,
    "UpdatedAt" timestamp with time zone NOT NULL,
    "CustomerId" uuid,
    "CustomerName" character varying(255) NOT NULL,
    "CustomerEmail" text NOT NULL,
    "CustomerPhone" text,
    "WhatsAppNumber" character varying(50),
    "DriverName" text,
    "DriverPhone" text,
    "DeliveryAddress" character varying(1000) NOT NULL,
    "OrderItemsJson" text NOT NULL,
    "Subtotal" numeric(18,2) NOT NULL,
    "DeliveryFee" numeric(18,2),
    "TotalDue" numeric(18,2) NOT NULL,
    "TrackingNumber" character varying(255),
    "LogisticsPartner" character varying(100),
    "ManualRiderName" character varying(255),
    "ManualTrackingInfo" character varying(255),
    "ApplicationUserId" text NOT NULL,
    "IsDeleted" boolean NOT NULL,
    "ApplicationUserId1" text,
    CONSTRAINT "PK_Order" PRIMARY KEY ("Id"),
    CONSTRAINT "FK_Order_Customers_CustomerId" FOREIGN KEY ("CustomerId") REFERENCES "Customers" ("Id"),
    CONSTRAINT "FK_Order_User_ApplicationUserId" FOREIGN KEY ("ApplicationUserId") REFERENCES "User" ("Id") ON DELETE RESTRICT,
    CONSTRAINT "FK_Order_User_ApplicationUserId1" FOREIGN KEY ("ApplicationUserId1") REFERENCES "User" ("Id")
);

CREATE TABLE "RefreshToken" (
    "Id" integer GENERATED BY DEFAULT AS IDENTITY,
    "Token" text NOT NULL,
    "Expires" timestamp with time zone NOT NULL,
    "Created" timestamp with time zone NOT NULL,
    "CreatedByIp" text NOT NULL,
    "Revoked" timestamp with time zone,
    "RevokedByIp" text NOT NULL,
    "ReplacedByToken" text NOT NULL,
    "ApplicationUserId" text,
    CONSTRAINT "PK_RefreshToken" PRIMARY KEY ("Id"),
    CONSTRAINT "FK_RefreshToken_User_ApplicationUserId" FOREIGN KEY ("ApplicationUserId") REFERENCES "User" ("Id")
);

CREATE TABLE "UserClaim" (
    "Id" integer GENERATED BY DEFAULT AS IDENTITY,
    "UserId" text NOT NULL,
    "ClaimType" text,
    "ClaimValue" text,
    CONSTRAINT "PK_UserClaim" PRIMARY KEY ("Id"),
    CONSTRAINT "FK_UserClaim_User_UserId" FOREIGN KEY ("UserId") REFERENCES "User" ("Id") ON DELETE CASCADE
);

CREATE TABLE "UserLogin" (
    "LoginProvider" text NOT NULL,
    "ProviderKey" text NOT NULL,
    "ProviderDisplayName" text,
    "UserId" text NOT NULL,
    CONSTRAINT "PK_UserLogin" PRIMARY KEY ("LoginProvider", "ProviderKey"),
    CONSTRAINT "FK_UserLogin_User_UserId" FOREIGN KEY ("UserId") REFERENCES "User" ("Id") ON DELETE CASCADE
);

CREATE TABLE "UserRole" (
    "UserId" text NOT NULL,
    "RoleId" text NOT NULL,
    CONSTRAINT "PK_UserRole" PRIMARY KEY ("UserId", "RoleId"),
    CONSTRAINT "FK_UserRole_Role_RoleId" FOREIGN KEY ("RoleId") REFERENCES "Role" ("Id") ON DELETE CASCADE,
    CONSTRAINT "FK_UserRole_User_UserId" FOREIGN KEY ("UserId") REFERENCES "User" ("Id") ON DELETE CASCADE
);

CREATE TABLE "UserToken" (
    "UserId" text NOT NULL,
    "LoginProvider" text NOT NULL,
    "Name" text NOT NULL,
    "Value" text,
    CONSTRAINT "PK_UserToken" PRIMARY KEY ("UserId", "LoginProvider", "Name"),
    CONSTRAINT "FK_UserToken_User_UserId" FOREIGN KEY ("UserId") REFERENCES "User" ("Id") ON DELETE CASCADE
);

CREATE INDEX "IX_Order_ApplicationUserId" ON "Order" ("ApplicationUserId");

CREATE INDEX "IX_Order_ApplicationUserId1" ON "Order" ("ApplicationUserId1");

CREATE INDEX "IX_Order_CustomerId" ON "Order" ("CustomerId");

CREATE INDEX "IX_RefreshToken_ApplicationUserId" ON "RefreshToken" ("ApplicationUserId");

CREATE UNIQUE INDEX "RoleNameIndex" ON "Role" ("NormalizedName");

CREATE INDEX "IX_RoleClaim_RoleId" ON "RoleClaim" ("RoleId");

CREATE INDEX "IX_RolePermission_PermissionId" ON "RolePermission" ("PermissionId");

CREATE INDEX "EmailIndex" ON "User" ("NormalizedEmail");

CREATE INDEX "IX_User_CompanyId" ON "User" ("CompanyId");

CREATE UNIQUE INDEX "UserNameIndex" ON "User" ("NormalizedUserName");

CREATE INDEX "IX_UserClaim_UserId" ON "UserClaim" ("UserId");

CREATE INDEX "IX_UserLogin_UserId" ON "UserLogin" ("UserId");

CREATE INDEX "IX_UserRole_RoleId" ON "UserRole" ("RoleId");

INSERT INTO "__EFMigrationsHistory" ("MigrationId", "ProductVersion")
VALUES ('20260531100522_InitPostgres', '8.0.0');

COMMIT;

